'use client';

import Link from 'next/link';

export default function TermsOfUsePage() {
  return (
    <main style={{ minHeight: '100vh', background: 'var(--void, #040711)', color: 'var(--ink, #f4f8ff)', padding: '64px 24px 120px' }}>
      <div style={{ maxWidth: '820px', margin: '0 auto' }}>
        <Link
          href="/"
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '8px',
            color: 'var(--cyan, #00e5ff)',
            fontSize: '13px',
            fontWeight: 600,
            marginBottom: '36px',
            textDecoration: 'none'
          }}
        >
          ← Return to Armelis Home
        </Link>

        <div style={{ borderBottom: '1px solid var(--line, #18324d)', paddingBottom: '24px', marginBottom: '36px' }}>
          <p style={{ color: 'var(--cyan, #00e5ff)', fontSize: '11px', fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', margin: '0 0 10px' }}>
            LEGAL COMPLIANCE &amp; OPEN SOURCE TERMS
          </p>
          <h1 style={{ fontFamily: "'Rajdhani', sans-serif", fontSize: 'clamp(36px, 5vw, 48px)', fontWeight: 800, margin: '0 0 10px', textTransform: 'uppercase' }}>
            Terms of Use
          </h1>
          <p style={{ color: 'var(--muted, #8ba2bb)', fontSize: '14px', margin: 0 }}>
            Effective: September 17, 2026 • Armelis Open Source Platform
          </p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '32px', fontSize: '15px', lineHeight: 1.75, color: '#cbd5e1' }}>
          <section>
            <h2 style={{ color: 'var(--ink, #ffffff)', fontSize: '20px', fontWeight: 700, margin: '0 0 12px' }}>
              1. Open-Source MIT License
            </h2>
            <p style={{ margin: 0 }}>
              Armelis is licensed and distributed under the permissive terms of the <strong>MIT License</strong>. You are granted permission, free of charge, to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software, subject to preserving the original copyright notice and permission notice.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--ink, #ffffff)', fontSize: '20px', fontWeight: 700, margin: '0 0 12px' }}>
              2. Disclaimer of Warranties
            </h2>
            <p style={{ margin: 0, textTransform: 'uppercase', fontSize: '13px', color: '#94a3b8' }}>
              THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--ink, #ffffff)', fontSize: '20px', fontWeight: 700, margin: '0 0 12px' }}>
              3. Defensive &amp; Ethical Utilization
            </h2>
            <p style={{ margin: 0 }}>
              Armelis is engineered strictly for defensive cybersecurity analysis, attack reachability visualization, and vulnerability elimination. Users agree to utilize Armelis solely against infrastructure, repositories, and applications for which they possess explicit, documented authorization to audit.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--ink, #ffffff)', fontSize: '20px', fontWeight: 700, margin: '0 0 12px' }}>
              4. AI Remediation Verification
            </h2>
            <p style={{ margin: 0 }}>
              Remediation prompts generated by Armelis for AI coding agents (such as Cursor, Claude Code, and GitHub Copilot) represent deterministic defensive suggestions based on detected choke points. Developers and security teams are solely responsible for testing and validating all pull requests before merging into production systems.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--ink, #ffffff)', fontSize: '20px', fontWeight: 700, margin: '0 0 12px' }}>
              5. Maintainer Attribution
            </h2>
            <p style={{ margin: 0 }}>
              Armelis is developed and maintained by <strong>Johan Vasquez</strong>. For project collaboration or questions regarding these terms, visit{' '}
              <a href="https://github.com/Johanvasquezdev/armelis" target="_blank" rel="noreferrer" style={{ color: 'var(--cyan, #00e5ff)' }}>
                github.com/Johanvasquezdev/armelis
              </a>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
